name: bashnovustools
base: core24
version: '0.1.2.1'
summary: BashNovusTools providing tools for deployment tasks and operations.
description: |
  A collection of Bash scripts packaged as a snap package.
  Includes multiple scripts like upgrade.sh, install-docker_engine.sh,
  install-docker-compose.sh, refresh-env.sh and restart-docker.sh

grade: devel
confinement: devmode

apps:
  upgrade-ubuntu:
    command: bin/update-ubuntu.sh
    environment:
      PATH: "$SNAP/bin:$PATH"

  install-docker-engine:
    command: bin/install-docker-engine.sh
    environment:
      PATH: "$SNAP/bin:$PATH"

  install-docker-compose:
    command: bin/install-docker-compose.sh
    environment:
      PATH: "$SNAP/bin:$PATH"

  restart-docker:
    command: bin/restart-docker.sh
    environment:
      PATH: "$SNAP/bin:$PATH"    

  refresh-env:
    command: bin/refresh-env.sh
    environment:
      PATH: "$SNAP/bin:$PATH"

parts:
  scripts:
    plugin: dump
    source: .
    organize:
      update-ubuntu.sh: bin/update-ubuntu.sh
      install-docker-engine.sh: bin/install-docker-engine.sh
      install-docker-compose.sh: bin/install-docker-compose.sh
      restart-docker.sh: bin/restart-docker.sh 
      refresh-env.sh: bin/refresh-env.sh
    override-build: |
      snapcraftctl build
      chmod 755 $SNAPCRAFT_PART_INSTALL/bin/*.sh
