name: Release
name: Release

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute VERSION
        id: v
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            # e.g. fallback for branch builds: use short SHA or skip
            echo "version=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create archive
        run: |
          mkdir -p dist
          VERSION="${{ steps.v.outputs.version }}"
          # Use the tag as the tree-ish if present, otherwise HEAD
          TREEISH="${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'HEAD' }}"
          git archive --format=zip --output="dist/BashNovusTools.${VERSION}.zip" "$TREEISH"

      # Only create a GitHub Release when this was a TAG push
      - name: Create Release (auto notes)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: dist/BashNovusTools.${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

